name: Create and publish a Docker image

on:
  push:
    tags: [v*]
env:
  repo_owner: "enishowk"
  repo_name: "debridarr"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.repo_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build and push the Docker image
        run: |
          docker build . --tag ghcr.io/${{ env.repo_owner }}/${{ env.repo_name }}:latest
          docker push ghcr.io/${{ env.repo_owner }}/${{ env.repo_name }}:latest
